name: riverpod_child_provider
description: A new Flutter project.
license: "MIT-0"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  riverpod_infinite_scroll: ^1.0.6
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

 